version: '3.8'

services:
  api:
    build: .
    ports:
      - "5005:5005"
      - "8888:8888"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./notebooks:/app/notebooks
    restart: always
